### ISSUE TITLE
ONNX demo

### ISSUE THREAD

**Issue by dpascualhe** [TheRoboticsClub/gsoc2021-Shashwat_Dalakoti#6]
For now, using a pre-trained human detection model:

- Store the model in ONNX format.
- Perform inference on image samples.
- Play around with onnxruntime/onnxruntime-gpu and report any issues with GPU integration.

**Comment by dpascualhe** [comment]
@shashwat623 could you push to this repo the code in [MNIST-PyTorch-To-ONNX](https://github.com/shashwat623/MNIST-PyTorch-To-ONNX)? You might add it as a submodule if that's more comfortable for you.

**Comment by shashwat623** [comment]
@dpascualhe Done
